spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: example
          uri: http://httpbin.org:80
          predicates:
            - Path=/get
        # - id: websocket_route
        #   uri: ws://localhost:7777
        #   predicates:
        #     - Path=/ws/**
        #   filters:
        #     - StripPrefix=1
server:
  port: 8080
  reactive:
    netty:
